import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";


import Banner from "../components/banner/banner";
import Card from "../components/Card/Card";
import coffeeStores from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      // coffeeStores: coffeeStores,
      coffeeStores,
    }
  }
}

export default function Home(props) {
  console.log("Hi getStaticProps");

  const handleOnBannerBtnClick = () => {
    console.log("It is the Banner button");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero"
          />
        </div>
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore, key) => {
            return (
              <Card
                key={key}
                name={coffeeStore.name}
                imgUrl={coffeeStore.imgUrl}
                href={`/coffee-store/${coffeeStore.id}`}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
}
